#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      local url_rust='https://static.rust-lang.org/dist/rust-1.11.0-x86_64-apple-darwin.pkg'
      local fnm_rust='rust-1.11.0-x86_64-apple-darwin.pkg'
      cache curl "$fnm_rust" "$url_rust"
      block compile pkg "${BASEBOX_CACHE}/curl/$fnm_rust"
      ;;

    Linux)
      local url_rust='https://static.rust-lang.org/dist/rust-1.11.0-x86_64-unknown-linux-gnu.tar.gz'
      local fnm_rust='rust-1.11.0-x86_64-unknown-linux-gnu.tar.gz'
      cache curl "$fnm_rust" "$url_rust"
      mkdir -p "$shome/vendor"
      (cd "$shome/vendor" && tar xvfz "${BASEBOX_CACHE}/curl/$fnm_rust")
      (cd "$shome/vendor/rust-1.11.0-x86_64-unknown-linux-gnu" && sudo ./install.sh --destdir="$shome/vendor/rust")
      ;;
  esac
}

bootstrap
