#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      local url_rust="https://static.rust-lang.org/dist/rust-${RUST_VERSION}-x86_64-apple-darwin.tar.gz"
      local fnm_rust="rust-${RUST_VERSION}-x86_64-apple-darwin.tar.gz"
      ;;

    Linux)
      local url_rust="https://static.rust-lang.org/dist/rust-${RUST_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      local fnm_rust="rust-${RUST_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      ;;
  esac

  cache curl "$fnm_rust" "$url_rust"
  mkdir -p "$shome/vendor"
  (cd "$shome/vendor" && tar xfz "/data/cache/curl/$fnm_rust")
  (set +f; cd "$shome/vendor/rust-${RUST_VERSION}-"* && ./install.sh --destdir="$shome/vendor/rust-${RUST_VERSION}" --verbose) || true
  rm -rf "$shome/vendor/rust-${RUST_VERSION}-"*
}

bootstrap
