#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      local url_rust="https://static.rust-lang.org/dist/rust-${RUST_VERSION}-x86_64-apple-darwin.tar.gz"
      local fnm_rust="rust-${RUST_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      cache curl "$fnm_rust" "$url_rust"
      mkdir -p "$shome/vendor"
      (cd "$shome/vendor" && tar xvfz "${BASEBOX_CACHE}/curl/$fnm_rust")
      (cd "$shome/vendor/rust-${RUST_VERSION}-x86_64-apple-darwin" && sudo ./install.sh --destdir="$shome/vendor/rust")
      ;;

    Linux)
      local url_rust="https://static.rust-lang.org/dist/rust-${RUST_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      local fnm_rust="rust-${RUST_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      cache curl "$fnm_rust" "$url_rust"
      mkdir -p "$shome/vendor"
      (cd "$shome/vendor" && tar xvfz "${BASEBOX_CACHE}/curl/$fnm_rust")
      (cd "$shome/vendor/rust-${RUST_VERSION}-x86_64-unknown-linux-gnu" && sudo ./install.sh --destdir="$shome/vendor/rust")
      ;;
  esac
}

bootstrap
