#!/usr/bin/env bash

function profile {
  local shome="${_rust_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"

  RUST_VERSION='1.14.0'
  PATH="$shome/bin:$shome/vendor/rust-${RUST_VERSION}/usr/local/bin:$PATH"
}

profile
