#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_rust="$(rustc --version 2>/dev/null | awk 'NR == 1 {print $2}')"
  local ver_cargo="$(cargo --version 2>/dev/null | awk 'NR == 1 {print $2}')"
  jq -n \
    --arg rust "$ver_rust" \
    --arg cargo "$ver_cargo" \
    '{rust: $rust, cargo: $cargo}'
}

version "$@"
